### ISSUE TITLE
The manual is incomprehensible.

### ISSUE THREAD

**Issue by itechnocrat** [quadroid/jcf-pascal-format#1]
Please forgive me!
- Why do you write this jcf-cli in the second step of manual when the repository is called jcf-pascal-format?
- Not clear how to open jcf.lpr project within jcf-cli/CommandLine/Lazarus folder; where jcf-cli/CommandLine/Lazarus directory?

**Comment by quadroid** [comment]
> Why do you write this jcf-cli in the second step of manual when the repository is called jcf-pascal-format?
> Not clear how to open jcf.lpr project within jcf-cli/CommandLine/Lazarus folder;

I didn't write anything of this. These parts are from the original description written by [Bee Jay](https://github.com/git-bee). I just left it as-is. From the readme: `Original description follows`.

> where jcf-cli/CommandLine/Lazarus directory?

The Lazarus project file is [pascal_format.lpi](https://github.com/quadroid/jcf-pascal-format/blob/main/App/pascal_format.lpi). There's no `.lpr`, instead [pascal_format.dpr](https://github.com/quadroid/jcf-pascal-format/blob/main/App/pascal_format.dpr) is shared between both Delphi and Lazarus.

You really have to be blind to not figure this out on your own.
